### PR TITLE
 trigger cyberark--secrets-provider-for-k8s build on success

### PR DESCRIPTION
**Pull request by eladkug**
What does this PR do?
If build success it will trigger cyberark--secrets-provider-for-k8s and will not wait for the result.

What ticket does this PR close?
#85 

Verified on Master as well.

### CODE REVIEW

**Comment by eladkug** [comment]
> Code looks good, but why do you want conjur-authn-k8s-client to trigger secrets-provider-for-k8s?

I want to verify any change on authn-k8s will not influence on my tests as well  (for example conjur-authn_failure verification)

**Comment by hughsaunders** [comment]
@eladkug In that case, why not pin the version of authn-k8s-client, then changes won't cause your tests to fail. You can have Jenkins regularly (eg daily) check for new versions and create a pull request against your own repo that will update to the latest version of authn-k8s-client, and if the tests on that PR succeed, merge it, if not communicate between the two teams to fix it. 

This method gives you a notification that a new verison is out (via the PR), and an opportunity to run tests against the new version without breaking master.

**Comment by eladkug** [comment]
Thanks for your input i will verify this again and if its irrelevant i will close the PR

**Comment by eladkug** [comment]
Decided to close this PR. Thanks for your inputs

**Pull request closed without merging**
