### PR TITLE
Use Conjur in Helm chart names

### LINKED ISSUE #306: Use 'conjur' in the name of Helm charts to distinguish them from other Cyberark charts
## Is your feature request related to a problem? Please describe.

The names of the following Conjur authentication Helm charts:
- helm/kubernetes-cluster-prep
- helm/application-namespace-prep
- helm/app-deploy
should be changed so that they include `conjur`. These Helm charts will be published to the
Cyberark Helm chart repository (https://github.com/cyberark/helm-charts), so they should
contain `conjur` so they can be distinguished from other (non-Conjur-related) CyberArk Helm charts.

## Describe the solution you would like

Helm charts listed above have names that distinguish them as being Conjur-related.

### PR DESCRIPTION
**Pull request by diverdane**
### What does this PR do?

The names of the following Conjur authentication Helm charts:

- helm/kubernetes-cluster-prep
- helm/application-namespace-prep
- helm/app-deploy

are being changed so that they include `Conjur`. These Helm charts will be
published to a general Cyberark Helm chart repository
(https://github.com/cyberark/helm-charts), so the names of the charts need
to be kept unique among all CyberArk Helm charts. Using `conjur` will
help to keep these charts distinct from non-Conjur Helm charts.

### What ticket does this PR close?
Resolves #306 

#### Change log
- [ ] The CHANGELOG has been updated, or
- [x] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [x] The changes in this PR do not require tests

#### Documentation
- [x] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

#### Manual tests
**If you are preparing for a release**, have you run the following manual tests to verify existing functionality continues to function as expected?
- [ ] Manually run [Kubernetes-Conjur demo](https://github.com/conjurdemos/kubernetes-conjur-demo) with a local authn-k8s client image build

### CODE REVIEW

**Comment by izgeri** [comment]
Ok, so going through this here is what I can tell:

The [Kubernetes docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) recommend using:
- `app.kubernetes.io/name` - The name of the application, eg `mysql`
- `app.kubernetes.io/component` - The component within the architecture, eg `database`
- `app.kubernetes.io/instance` - A unique name identifying the instance of an application, eg `mysql-abcde`
- `app.kubernetes.io/part-of` - The name of a higher level application this one is part of, eg `wordpress`

I propose we have ONE higher level application `part-of` that is just `conjur-config`

Then we can have the following `component`s:
- `conjur-cluster-config`
- `conjur-namespace-config`
- `conjur-app-config`

And the following `instance`s:
- `conjur-clusterrole` (in `conjur-cluster-config` component; name can be the same)
- `conjur-golden-configmap` (in `conjur-cluster-config` component; name can be the same)
- `conjur-serviceaccount` (in `conjur-cluster-config` component; name can be the same)
- `conjur-{{ NAMESPACE }}-rolebinding` (in `conjur-namespace-config` component; name can be `conjur-rolebinding`)
- `conjur-{{ NAMESPACE }}-configmap` (in `conjur-namespace-config` component; name can be `conjur-connect-configmap`)
- `conjur-{{ ?? app name ?? }}-configmap` (in `conjur-app-config` component; name can be `conjur-authn-configmap`)

If you put this all together, it gives you the set of `app.kubernetes.io` annotations the different K8s resources need. I propose we either use the `component` or `name` value for the `conjur.org/name` field. 

Does this make sense? Would you change anything from what I recommend, and if so, what? Let's agree on this before editing the templates any further.

**Comment by rpothier** [comment]
When these Helm charts get added to the helm charts repo, should they be named `conjur-config-*` so that the user can search for `helm search repo -l cyberark/conjur-config` ?

**Comment by diverdane** [comment]
@izgeri and @rpothier, thanks for taking a look at these! I agree that we should hash these out now and avoid thrashing across repositories, or having to go through deprecation if we don't get it right from the beginning (e.g. if customers build tooling based on these labels).

> I propose we have ONE higher level application `part-of` that is just `conjur-config`

YES! This makes sense.

> Then we can have the following `component`s:
> 
> * `conjur-cluster-config`
> * `conjur-namespace-config`
> * `conjur-app-config`

For `component`, I'm thinking we might want values that match the logical role that each object is providing for Conjur config.

I'm basing this on the Kubernetes example where the `mysql` Pod is assigned a `component` value of `database`. Extending the example, I would assume that there could be a server Pod for the `wordpress` application with a `component` value of `server`, and maybe there's an NGINX that has `component` value of `reverse-proxy` or something like that?

Based on this thinking, the `component` values could be:

- `conjur-permissions` or just `clusterrole`                       for Conjur ClusterRole
- `conjur-reference-config` or `conjur-golden-config`.  for Conjur golden ConfigMap
- `conjur-kubernetes-identity` or just `serviceaccount` for Conjur ServiceAccount
- `conjur-namespace-access` or just `rolebinding`        for Conjur RoleBinding
- `conjur-connect-config`                                                   for Conjur connect ConfigMap
- `conjur-app-authn`                                                            for application's Conjur authn ConfigMap

Let me know if I'm overthinking this, or I have the wrong interpretation for the Kubernetes `component` field.

> And the following `instance`s:
> 
> * `conjur-clusterrole` (in `conjur-cluster-config` component; name can be the same)
> * `conjur-golden-configmap` (in `conjur-cluster-config` component; name can be the same)
> * `conjur-serviceaccount` (in `conjur-cluster-config` component; name can be the same)
> * `conjur-{{ NAMESPACE }}-rolebinding` (in `conjur-namespace-config` component; name can be `conjur-rolebinding`)
> * `conjur-{{ NAMESPACE }}-configmap` (in `conjur-namespace-config` component; name can be `conjur-connect-configmap`)
> * `conjur-{{ ?? app name ?? }}-configmap` (in `conjur-app-config` component; name can be `conjur-authn-configmap`)

YES! Perfect!!! I hadn't thought through that there will only be one ClusterRole, Golden ConfigMap, and ServiceAccount (at least in a given Namespace), so we can use a fixed `instance` value for these.

> I propose we either use the `component` or `name` value for the `conjur.org/name` field.

I believe that using the `name` as the value for `conjur.org/name` is the best choice. My thinking is that folks will want to find or filter based on a fixed (or generalized) value for the name. For example, if we want to find ALL Conjur connect ConfigMaps in the cluster, we would filter ConfigMaps based on the very general label:

```
    conjur.org/name=conjur-connect-configmap
```

There would be no real value add if we were to filter based on the very specific:
```
    conjur.org/name=conjur-{{ NAMESPACE }}-configmap
```
since this would only find one Conjur connect ConfigMap at a time.

**Comment by diverdane** [comment]
@izgeri , @rpothier ,

Are the proposed names for the Helm charts okay? I'm up for any suggestions/improvements:

- `conjur-kubernetes-cluster-prep`
- `conjur-app-namespace-prep`
- `conjur-app-deploy`

**Comment by diverdane** [comment]
@izgeri and @rpothier , 
I've updated this PR (#308 ) and PR #304 based on review comments.

**Review by rpothier — APPROVED** [review]
LGTM

**Pull request merged**
